[build]
  base = "quoteapi"
  command = "npm run build"
  publish = "quoteapi/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
NODE_OPTIONS = "--max_old_space_size=4096"